paths:
  - name: products
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001

  - name: categories
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001

  - name: orders
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001
