{
 "title": "Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": {
     "query": "label_values(tsgen_requests_total{}, job)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(tsgen_requests_total{url!~\".*(favicon|api).*\",  job=\"$job\"}, url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"2.*\", job=\"$job\"}[$__interval:30s])) by()",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(tsgen_requests_total{code=~\"2.*\", job=\"$job\"}[$__interval:30s])) by()",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"4.*\", job=\"$job\"}[$__interval:30s])) by()",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"5.*\", job=\"$job\"}[$__interval:30s])) by()",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(tsgen_request_duration_seconds_bucket{job=\"$job\"}[5m:30s])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(.75, sum(rate(tsgen_request_duration_seconds_bucket{job=\"$job\"}[5m:30s])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(.90, sum(rate(tsgen_request_duration_seconds_bucket{job=\"$job\"}[5m:30s])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tsgen_request_duration_seconds_bucket{job=\"$job\"}[5m:30s])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "$path Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "path" },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"2.*\", job=\"$job\", url=\"$path\"}[$__interval:30s])) by()",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(tsgen_requests_total{code=~\"2.*\", job=\"$job\", url=\"$path\"}[$__interval:30s])) by()",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"4.*\", job=\"$job\", url=\"$path\"}[$__interval:30s])) by(code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(increase(tsgen_requests_total{code=~\"5.*\", job=\"$job\", url=\"$path\"}[$__interval:30s])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}