paths:
  # paths names based on Fibonacci sequence [2, 89]
  - name: e0002pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0003pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0005pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0008pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0013pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0021pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0034pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0055pct
    faults:
      - code: 500
        rate: 0.001

  - name: e0089pct
    faults:
      - code: 500
        rate: 0.001
