paths:
  - name: stores
    response_time: 90ms
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001

  - name: langs
    response_time: 50ms
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001

  - name: customers
    response_time: 110ms
    faults:
      - code: 500
        rate: 0.001
      - code: 401
        rate: 0.001
