global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerting.rules.yml
  - /etc/prometheus/recording.rules.yml

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090

- job_name: pushgateway
  honor_labels: true
  metrics_path: /metrics
  static_configs:
  - targets:
    - pushgateway:9091

- job_name: tsgen
  metrics_path: /metrics
  static_configs:
  - targets:
    - tsgen:8080
