version: '3.2'

services:
  tsgen:
    image: tsgen
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./tsgen/config.yml:/etc/tsgen/config.yml

  prometheus:
    image: prom/prometheus:v2.29.2
    restart: unless-stopped
    ports:
      - "9090:9090"
    user: "1000:1000"
    volumes:
      - ../_common/prometheus/etc/alerting.rules.yml:/etc/prometheus/alerting.rules.yml
      - ../_common/prometheus/etc/recording.rules.yml:/etc/prometheus/recording.rules.yml
      - ./prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:8.1.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../_common/grafana/data/:/var/lib/grafana
      - ../_common/grafana/dashboards/:/var/lib/dashboards
      - ../_common/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../_common/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
