paths:
  # paths names based on Fibonacci sequence [2, 89]
  - name: e2pct
    response_time: 2ms
    faults:
      - code: 500
        rate: 0.001

  - name: e3pct
    response_time: 3ms
    faults:
      - code: 500
        rate: 0.001

  - name: e5pct
    response_time: 5ms
    faults:
      - code: 500
        rate: 0.001

  - name: e8pct
    response_time: 8ms
    faults:
      - code: 500
        rate: 0.001


  - name: e13pct
    response_time: 13ms
    faults:
      - code: 500
        rate: 0.001

  - name: e21pct
    response_time: 21ms
    faults:
      - code: 500
        rate: 0.001

  - name: e34pct
    response_time: 34ms
    faults:
      - code: 500
        rate: 0.001

  - name: e55pct
    response_time: 55ms
    faults:
      - code: 500
        rate: 0.001

  - name: e89pct
    response_time: 89ms
    faults:
      - code: 500
        rate: 0.001
